routes/web.php
<?php
//Route::get('/', function () {
//    return view('welcome');
//});
// 前台首页路由
Route::group(['namespace'=>'Home','as'=>'home.'],function (){
    // 前台首页路由
    Route::get('/','HomeController@index')->name('index');
    // 详情页路由
    Route::get('/content/{good}/{product?}','HomeController@content')->name('content');
    // 列表页路由
    Route::get('/lists/{category}','HomeController@lists')->name('lists');

    // 前台登录、退出、注册路由
    Route::get('/login','LoginController@loginForm')->name('login');
    Route::post('/login','LoginController@login')->name('login');
    Route::get('/logout','LoginController@logout')->name('logout');
    Route::get('/regist','RegistController@regist')->name('regist');
    Route::post('/regist','RegistController@store')->name('regist');
    // 微信支付异步通知路由,异步是微信的请求，对于微信而言，不存在什么令牌一说，所以要想请求到laravel里面的数据，
    // 就应该把微信请求的路由规则加入白名单，即 中间件里面的 verifycsrftoken文件设置就可以了。
    Route::post('wxPayResult','PayController@wxPayResult')->name('wxPayResult');
});
/**
 *  需要验证的路由
 */
Route::group(['middleware'=>'auth.login','namespace'=>'Home','as'=>'home.'],function (){
    // 加入购物车路由
    Route::get('/addCart/{good}/{product}/{num}','CartController@addCart')->name('addCart');
    // 立即购买
    Route::post('quickBuy','CartController@quickBuy')->name('quickBuy');
    // 我的购物车
    Route::get('/myCart','CartController@myCart')->name('myCart');
    // 删除购物车数据路由
    Route::get('/deleteCart/{cart}','CartController@delete')->name('myCart.delete');
    // 购物车数量加1
    Route::get('/plus/{cart}','CartController@plus')->name('myCart.plus');
    // 购物车数量减1
    Route::get('/minus/{cart}','CartController@minus')->name('myCart.minus');
    // 个人中心路由
    Route::get('/center/{bianliang}','CenterController@index')->name('center');
    // 个人中心修改密码路由
    Route::put('/center/changePassword/','UserController@changPassword')->name('changePassword');
    // 个人中心修改个人信息的路由
    Route::put('/center/gerenXinxi','UserController@gerenXinxi')->name('gerenXinxi');
    // 个人中心收货人地址资源路由
    Route::resource('/center/address','AddressController');
    // 设置默认地址路由
    Route::get('/center/setDefault/{address}','AddressController@setDefault')->name('setDefault');
    // 去结算的订单列表页面
    Route::get('/order_list','OrderController@orders')->name('order_list');
    // 订单的资源路由
    Route::resource('/order','OrderController');
    // 异步删除我的订单路由
    Route::get('/delOrder/{order_id}','CenterController@delOrder')->name('delOrder');
    // 提交订单成功以后，跳转的支付订单路由
    Route::get('/pay/{order_bianhao}','PayController@index')->name('pay');
    //检测订单支付状态
    Route::post('checkOrderStatus','PayController@checkOrderStatus')->name('checkOrderStatus');
});
/*
 *【后台登录验证的路由组】
 */
Route::group(['middleware'=>'admin.auth','prefix'=>'admin','namespace'=>'Admin','as'=>'admin.'],function (){
    Route::get('/','AdminController@index')->name('index');
    // 分类管理资源路由
    Route::resource('/category','CategoryController');
    // 获取子分类的路由
    Route::get('/getSonCategory/{id}','CategoryController@getSonCategory')->name('getSonCategory');
    // 商品管理资源路由
    Route::resource('/goods','GoodsController');
    // 后台，订单管理路由
    Route::resource('order','OrderController');
    // 幻灯片管理
    Route::resource('slide','SlideController');
    // 权限列表路由
    Route::get('admin/permission','PermissionController@index')->name('permission');
    // 角色资源路由
    Route::resource('admin/role','RoleController');

});

/*
 * 【后台登录不需要验证的路由组】
 */
Route::group(['prefix'=>'admin','namespace'=>'Admin','as'=>'admin.'],function (){
    Route::get('/login','LoginController@loginForm')->name('login');
    Route::post('/login','LoginController@login')->name('login');
    Route::get('/logout','LoginController@logout')->name('logout');
});

/**
 * 公共控制器  图片上传类
 */
Route::group(
    ['prefix' => 'common', 'namespace' => 'Common', 'as' => 'common.'],
    function () {
        Route::any('uploader/make', 'UploaderController@make')->name('uploader.make');
        Route::any('uploader/lists', 'UploaderController@lists')->name('uploader.lists');
        // layui图片上传路由
        Route::any('uploader/layuiUpload','UploaderController@layuiUpload')->name('uploader.layuiUpload');
        // 发送验证码类
        Route::any('code/send','CodeController@send')->name('code.send');
    }
);

resources/views/admin/index.blade.php
@extends('layouts.admin')
@section('content')
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">哈喽啊</h3>
                <p class="card-text">
                    感谢您的光临！
                </p>
                <a href="/" class="btn btn-primary">去前台</a>
            </div>
        </div>
@endsection

resources/views/admin/login.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
    <!-- Libs CSS -->
    <link rel="stylesheet" href="{{asset('org/assets')}}/fonts/feather/feather.min.css">
    <link rel="stylesheet" href="{{asset('org/assets')}}/libs/highlight/styles/vs2015.min.css">
    <link rel="stylesheet" href="{{asset('org/assets')}}/libs/quill/dist/quill.core.css">
    <link rel="stylesheet" href="{{asset('org/assets')}}/libs/select2/dist/css/select2.min.css">
    <link rel="stylesheet" href="{{asset('org/assets')}}/libs/flatpickr/dist/flatpickr.min.css">
    <!-- Theme CSS -->
    <link rel="stylesheet" href="{{asset('org/assets')}}/css/theme.min.css">
    @include('layouts._hdjs')
    @include('layouts._message')
    <title>后台登录页面</title>
</head>
<body class="d-flex align-items-center bg-white border-top-2 border-primary">

<!-- CONTENT-->
<div class="container">
    <div class="row align-items-center">
        <div class="col-12 col-md-6 offset-xl-2 offset-md-1 order-md-2 mb-5 mb-md-0">
            <!-- Image -->
            <div class="text-center">
                <img src="{{asset('org/assets')}}/img/illustrations/happiness.svg" alt="..." class="img-fluid">
            </div>
        </div>
        <div class="col-12 col-md-5 col-xl-4 order-md-1 my-5">
            <h1 class="display-4 text-center mb-3">
               后台登录
            </h1>
            <!-- Form -->
            <form action="{{route('admin.login')}}" method="post">
                @csrf
                <!-- Email address -->
                <div class="form-group">
                    <label>用户名</label>
                    <input type="text" name='username' class="form-control" placeholder="请输入用户名">
                </div>
                <!-- Password -->
                <div class="form-group">
                    <div class="row">
                        <div class="col">
                            <label>密码</label>
                        </div>
                    </div>
                    <div class="input-group input-group-merge">
                        <input type="password" name="password" class="form-control form-control-appended" placeholder="请输入密码">
                        <div class="input-group-append">
                  <span class="input-group-text">
                    <i class="fe fe-eye"></i>
                  </span>
                        </div>
                    </div>
                </div>
                <button class="btn btn-lg btn-block btn-primary mb-3">
                   登录
                </button>
            </form>

        </div>
    </div> <!-- / .row -->
</div> <!-- / .container -->

<!-- JAVASCRIPT-->
{{--<!-- Libs JS -->--}}
{{--<script src="{{asset('org/assets')}}/libs/jquery/dist/jquery.min.js"></script>--}}
{{--<script src="{{asset('org/assets')}}/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>--}}
{{--<script src="{{asset('org/assets')}}/libs/chart.js/dist/Chart.min.js"></script>--}}
{{--<script src="{{asset('org/assets')}}/libs/chart.js/Chart.extension.min.js"></script>--}}
{{--<script src="{{asset('org/assets')}}/libs/highlight/highlight.pack.min.js"></script>--}}
{{--<script src="{{asset('org/assets')}}/libs/flatpickr/dist/flatpickr.min.js"></script>--}}
{{--<script src="{{asset('org/assets')}}/libs/jquery-mask-plugin/dist/jquery.mask.min.js"></script>--}}
{{--<script src="{{asset('org/assets')}}/libs/list.js/dist/list.min.js"></script>--}}
{{--<script src="{{asset('org/assets')}}/libs/quill/dist/quill.min.js"></script>--}}
{{--<script src="{{asset('org/assets')}}/libs/dropzone/dist/min/dropzone.min.js"></script>--}}
{{--<script src="{{asset('org/assets')}}/libs/select2/dist/js/select2.min.js"></script>--}}
{{--<!-- Theme JS -->--}}
{{--<script src="{{asset('org/assets')}}/js/theme.min.js"></script>--}}

</body>
</html>

resources/views/admin/permission_index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="card">
        <div class="card-body">
            @foreach($modules as $module)
                <div class="card">
                    <div class="card-header font-weight-bold">
                        {{$module['name']}}
                    </div>
                    <div class="card-body">
                        <div class="row">
                            {{--循环模型里面的权限配置项数据，得到的是二维数组，进行比遍历--}}
                            @foreach($module['permission'] as $permission)
                                <div class="col-4 mb-2 mt-2">
                                    {{--把得到的一位数组的title，和name值都取出来进行展示--}}
                                    {{$permission['title']}}【{{$permission['name']}}】
                                </div>
                            @endforeach

                        </div>
                    </div>

                </div>
            @endforeach
        </div>
    </div>
@endsection

resources/views/admin/user_index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs nav-overflow header-tabs">
                <li class="nav-item mt-0">
                    <a href="{{route('admin.index')}}" class="nav-link">
                        用户列表
                    </a>
                </li>
            </ul>
        </div>

        <div class="card-body small">
            <table class="table text-center">
                <thead>
                <tr>
                    <th>编号</th>
                    <th>用户名</th>
                    <th>所属角色</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                    <tr>
                        <td scope="row">{{$user['id']}}</td>
                        <td>{{$user['username']}}</td>
                        {{--因为Role方法返回的是一个对象集合，也就是二维数组，所以要遍历等到某一个记录对象--}}
                        <td>
                            {{--@foreach($user->Role as $role)--}}
                                {{--<span class="badge badge-info"> {{$role['title']}} </span>--}}
                            {{--@endforeach--}}
                        </td>
                        <td>
                            <div class="btn-group btn-group-sm" role="group" aria-label="First group">
                                <a href=" " class="btn btn-light">分配角色</a>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
{{--        {{$users->links()}}--}}
    </div>
@endsection