routes/web.php
<?php
//Route::get('/', function () {
//    return view('welcome');
//});
// 前台首页路由
Route::group(['namespace'=>'Home','as'=>'home.'],function (){
    // 前台首页路由
    Route::get('/','HomeController@index')->name('index');
    // 详情页路由
    Route::get('/content/{good}/{product?}','HomeController@content')->name('content');
    // 列表页路由
    Route::get('/lists/{category}','HomeController@lists')->name('lists');

    // 前台登录、退出、注册路由
    Route::get('/login','LoginController@loginForm')->name('login');
    Route::post('/login','LoginController@login')->name('login');
    Route::get('/logout','LoginController@logout')->name('logout');
    Route::get('/regist','RegistController@regist')->name('regist');
    Route::post('/regist','RegistController@store')->name('regist');
    // 微信支付异步通知路由,异步是微信的请求，对于微信而言，不存在什么令牌一说，所以要想请求到laravel里面的数据，
    // 就应该把微信请求的路由规则加入白名单，即 中间件里面的 verifycsrftoken文件设置就可以了。
    Route::post('wxPayResult','PayController@wxPayResult')->name('wxPayResult');
});
/**
 *  需要验证的路由
 */
Route::group(['middleware'=>'auth.login','namespace'=>'Home','as'=>'home.'],function (){
    // 加入购物车路由
    Route::get('/addCart/{good}/{product}/{num}','CartController@addCart')->name('addCart');
    // 立即购买
    Route::post('quickBuy','CartController@quickBuy')->name('quickBuy');
    // 我的购物车
    Route::get('/myCart','CartController@myCart')->name('myCart');
    // 删除购物车数据路由
    Route::get('/deleteCart/{cart}','CartController@delete')->name('myCart.delete');
    // 购物车数量加1
    Route::get('/plus/{cart}','CartController@plus')->name('myCart.plus');
    // 购物车数量减1
    Route::get('/minus/{cart}','CartController@minus')->name('myCart.minus');
    // 个人中心路由
    Route::get('/center/{bianliang}','CenterController@index')->name('center');
    // 个人中心修改密码路由
    Route::put('/center/changePassword/','UserController@changPassword')->name('changePassword');
    // 个人中心修改个人信息的路由
    Route::put('/center/gerenXinxi','UserController@gerenXinxi')->name('gerenXinxi');
    // 个人中心收货人地址资源路由
    Route::resource('/center/address','AddressController');
    // 设置默认地址路由
    Route::get('/center/setDefault/{address}','AddressController@setDefault')->name('setDefault');
    // 去结算的订单列表页面
    Route::get('/order_list','OrderController@orders')->name('order_list');
    // 订单的资源路由
    Route::resource('/order','OrderController');
    // 异步删除我的订单路由
    Route::get('/delOrder/{order_id}','CenterController@delOrder')->name('delOrder');
    // 提交订单成功以后，跳转的支付订单路由
    Route::get('/pay/{order_bianhao}','PayController@index')->name('pay');
    //检测订单支付状态
    Route::post('checkOrderStatus','PayController@checkOrderStatus')->name('checkOrderStatus');
});
/*
 *【后台登录验证的路由组】
 */
Route::group(['middleware'=>'admin.auth','prefix'=>'admin','namespace'=>'Admin','as'=>'admin.'],function (){
    Route::get('/','AdminController@index')->name('index');
    // 分类管理资源路由
    Route::resource('/category','CategoryController');
    // 获取子分类的路由
    Route::get('/getSonCategory/{id}','CategoryController@getSonCategory')->name('getSonCategory');
    // 商品管理资源路由
    Route::resource('/goods','GoodsController');
    // 后台，订单管理路由
    Route::resource('order','OrderController');
    // 幻灯片管理
    Route::resource('slide','SlideController');
    // 权限列表路由
    Route::get('admin/permission','PermissionController@index')->name('permission');
    // 角色资源路由
    Route::resource('admin/role','RoleController');

});

/*
 * 【后台登录不需要验证的路由组】
 */
Route::group(['prefix'=>'admin','namespace'=>'Admin','as'=>'admin.'],function (){
    Route::get('/login','LoginController@loginForm')->name('login');
    Route::post('/login','LoginController@login')->name('login');
    Route::get('/logout','LoginController@logout')->name('logout');
});

/**
 * 公共控制器  图片上传类
 */
Route::group(
    ['prefix' => 'common', 'namespace' => 'Common', 'as' => 'common.'],
    function () {
        Route::any('uploader/make', 'UploaderController@make')->name('uploader.make');
        Route::any('uploader/lists', 'UploaderController@lists')->name('uploader.lists');
        // layui图片上传路由
        Route::any('uploader/layuiUpload','UploaderController@layuiUpload')->name('uploader.layuiUpload');
        // 发送验证码类
        Route::any('code/send','CodeController@send')->name('code.send');
    }
);

app/Models/Category.php
<?php

namespace App\Models;

use houdunwang\arr\Arr;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['title', 'parent_id', 'icon'];

    /**
     * 重点：在分类操作时，主要看站立的角度问题，角度不同使用的方法就不同 。都是相对而言的
     * 自关联：找子类 或者 父类的方法注意事项：
     * 1. 如果是找子类，是一对多的关系
     * 2. 如果是找父类，是多对一的关系
     * 3. belongTo 和 hasMany 区别：
     * 语法结构： 都是3个参数，
     *  第一个都是被关联的对象模型，
     *  第二个参数： 如果是belongTo，则是内键，如果是hanMany则是外键
     *  第三个参数跟第二各参数恰恰相反
     */
    // ** 找父类 返回值: 所有父类数据 **
    public function parent_name()
    {
        return $this->belongsTo(Category::class, 'parent_id', 'id');
    }

    // 通过自关联来获取子类数据 ,找孩子是一对多的关系，所以用hasMany方法
    public function category()
    {
        return $this->hasMany(Category::class, 'parent_id', 'id');
    }


    // ** 找子类 返回值：所有子类数据 **
    public function getSonCategory($id)
    {
        $categories = Category::where('parent_id', $id)->get();

        return $categories;
    }

    // 获取分类的树状结构图
    public function getTreeCategory()
    {
        // 首先要获取到所有的数据
        $data = Category::get()->toArray();

        return Arr::tree($data, 'title', 'id', 'parent_id');
    }

    // 获取所有的分类数据,主要在编辑的时候使用
    public function getAllCategory()
    {
        // 首先，获取分类的树状结构
        $categories = $this->getTreeCategory();
        // 确定当前编辑的数据的级别，根据级别来判断是否可用
        // 定义一个空变量，来接收增加了级别编号的当前编辑的数据
        $currentCategory = [];
        foreach ($categories as $category) {
            if ($category['id'] == $this['id']) {
                // $currentCategory 代表当前正在编辑的数据
                $currentCategory = $category;
            }
        }
        // 用循环到的数据的级别跟当前编辑的数据级别进行比较，如果大于或等于当前就不可选
        foreach ($categories as $k => $category) {
            // 大于等于当前_level不选中
            if ($category['_level'] >= $currentCategory['_level']) {
                $categories[$k]['_disabled'] = 'disabled';
            } else {
                $categories[$k]['_disabled'] = '';
            }
            // 找当前编辑的数据父级，如果找到了就默认选中selected
            if ($category['id'] == $currentCategory['parent_id']) {
                $categories[$k]['_selected'] = 'selected';
            } else {
                $categories[$k]['_selected'] = '';
            }
        }

        return $categories;
    }

    /**
     * 判断某个分类是否有子分类，返回值为真，假
     */
    public function hasChild($category)
    {
        // 调用arr组件的判断是否有子集方法,如果有,返回真,如果没有,返回假
        return Arr::hasChild($this->getAllCategory(), $category['id'], 'parent_id');
    }


    /**
     *  通过二级分类分类找三级分类下的商品的方法
     *  而且是一个分类下面找一条数据
     */
    public function getGoods()
    {
        // 首先要获取到二级分类下三级分类数据 ，找到的是一个对象集合,我们只想一页展示8个3级分类的数据，所以
        // 这里做了限制条件为8 ，而且是一个3级分类下面取一个数据
        $sonCategory = $this->category()->limit(8)->get();
        // 思路：找商品，就应该找到最低级的3级分类才可以找到分类对应的商品，所以我们这里如上是二级分类调用了getGoods方法，
        // 从而可以获取到二级分类对应下的所有三级分类，根据3级分类的ID 是否在某一个商品的category_id数组中，就可以
        // 就可以确定当前3级分类下有哪些商品，这里3级分类有多个，商品更是有多个，所以用分类去匹配商品数据，只能是
        // 每一个分类都去匹配一次所有的商品，商品要循环，分类是外部循环，所以涉及到了循环的嵌套问题。
        $goodsIds = [];
        foreach ($sonCategory as $category) { // 得到的是每一个3级分类，进行循环比较
            // 求出所有的商品数据
            $goods = Goods::orderby('id', 'DESC')->get();
            //  对所有的商品数据再次进行循环，判断外部循环的分类ID是否在某一个商品的category_id内
            foreach ($goods as $good) {
                // 如果当前分类的ID 在 商品数据的category，说明该商品在当前分类下
                // 把商品的ID拿出来，存在一个数组中，一会儿一次性取出来尽心循环
                if (in_array($category['id'], $good['category_id'])) {
                    $goodsIds[] = $good['id'];
                    break; // 当某一个分类下找到了，就跳出循环，那么这样就可以实现一个分类下找到一个数据的功能
                }
            }

        }
        // 截止这里，只是把商品的ID求出来了，而且是限制了最多8条记录
        // 接下来就是要获取这些数据了,从而就可以后取道每一个3级分类下的最新的一个商品数据了
        // 求出商品ID在循环出来的ID集合中的所有商品
        $category_goods = Goods::whereIn('id', $goodsIds)->get();

        return $category_goods;
    }

    // 获取某一个分类下面的所有的商品数据
    public function getCategoryGoods()
    {
        $goods = Goods::get();
        $goodsIds = [];
        foreach($goods as $good){
            if(in_array($this->id,$good['category_id'])){
                $goodsIds[] = $good['id'];
            }
        }
        $categoryGoods = Goods::whereIn('id',$goodsIds)->get();
        // 把得到的所有分类数据返回去
        return $categoryGoods;
    }

    // 获取当前分类的父级分类
    public function getFatherCategory(){
        $fatherCategory = Arr::parentChannel($this->getTreeCategory(), $this->id, $fieldPri = 'id', $fieldPid = 'parent_id');
        return array_reverse($fatherCategory);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function index()
    {
        // 因为在列表页数据很多，所以这里用分页的方法来获取数据
        $categories = Category::paginate(10);
        return view('category.index', compact('categories'));
    }

    public function create(Category $category)
    {
        // 因为在添加是，要选择是哪个分类下的数据，所以要获取所有分类数据，用下拉框表单来遍历数据
        $categories = $category->getTreeCategory();
        return view('category.create', compact('categories'));
    }

    public function store(Request $request)
    {
        // 因为每次添加的是一条数据，所以这里用Crete方法就可以添加数据了
        Category::create($request->all());
        return redirect(route('admin.category.index'))->with('success', '添加成功');
    }

    public function show(Category $category)
    {
        //
    }

    public function edit(Category $category)
    {
        // 因为是编辑单条数据，所以这里用依赖注入的形式，获取到当前被编辑的单条数据对象进行处理
        $categories = $category->getAllCategory();
        return view('category.edit', compact('category', 'categories'));
    }

    public function update(Request $request, Category $category)
    {
        $category->update($request->all());
        return redirect(route('admin.category.index'))->with('success', '修改成功');
    }

    public function destroy(Category $category)
    {
        // 检测当前需要删除的分类是否有子分类,如果有,不让删除
        if ($category->hasChild($category)) {
            return back()->with('error', '请先删除子分类再来 (⊙﹏⊙)');
        }
        $category->delete();
        return back()->with('success', '删除成功！');
    }

    /**
     * 获取某个分类的子分类的方法
     */
    public function getSonCategory($id){
        $categories = Category::where('parent_id',$id)->get();
        return $categories;
    }
}

resources/views/category/create.blade.php
@extends('layouts.admin')
@section('content')
    <div class="card">
        <div class="card-body">
            <ul class="nav nav-tabs nav-overflow header-tabs">
                <li class="nav-item">
                    <a href="{{route('admin.category.index')}}" class="nav-link pb-3 ">
                        分类列表
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('admin.category.create')}}" class="nav-link pb-3
                     {{active_class(if_route('admin.category.create'),'active')}}">
                        添加分类
                    </a>
                </li>
            </ul>
        </div>
        <form action="{{route('admin.category.store')}}" method="post">
            @csrf
            <div class="card-body">
                <div class="card">
                    <div class="card-header">
                        基本设置
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label>分类名称</label>
                            <input type="text" name="title" class="form-control" placeholder="请输入分类名称"
                                   aria-describedby="helpId">
                        </div>
                        <div class="form-group">
                            <label for="">父级分类</label>
                            <select class="form-control" name="parent_id">
                                <option value="0">顶级分类</option>
                                @foreach($categories as $category)
                                    <option value="{{$category['id']}}">{!! $category['_title'] !!}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="">分类图片</label>
                            <div class="col-12">
                                <div class="input-group ">
                                    <input class="form-control" name="icon" readonly="" value="">
                                    <div class="input-group-append">
                                        <button onclick="upImagePc(this)" class="btn btn-secondary" type="button">单图上传
                                        </button>
                                    </div>
                                </div>
                                <div style="display: inline-block;position: relative;">
                                    <img src="/images/nopic.jpg" class="img-responsive img-thumbnail" width="150">
                                    <em class="close" style="position: absolute;top: 3px;right: 8px;" title="删除这张图片"
                                        onclick="removeImg(this)">×</em>
                                </div>
                            </div>
                        </div>
                        <script>
                            require(['hdjs', 'bootstrap']);

                            //上传图片
                            function upImagePc() {
                                require(['hdjs'], function (hdjs) {
                                    var options = {
                                        multiple: false,//是否允许多图上传
                                        //data是向后台服务器提交的POST数据
                                        data: {name: '后盾人', year: 2099},
                                    };
                                    hdjs.image(function (images) {
                                        //上传成功的图片，数组类型
                                        $("[name='icon']").val(images[0]);
                                        $(".img-thumbnail").attr('src', images[0]);
                                    }, options)
                                });
                            }

                            //移除图片
                            function removeImg(obj) {
                                $(obj).prev('img').attr('src', '../dist/static/image/nopic.jpg');
                                $(obj).parent().prev().find('input').val('');
                            }
                        </script>
                        <div class="form-group">
                            <label>分类描述</label>
                            <textarea name="description" style="resize: none" class="form-control" rows="3"></textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer text-muted">
                <button class="btn btn-primary btn-sm">保存提交</button>
            </div>
        </form>
    </div>
@endsection

resources/views/category/edit.blade.php
@extends('layouts.admin')
@section('content')
    <div class="card">
        <div class="card-body">
            <ul class="nav nav-tabs nav-overflow header-tabs">
                <li class="nav-item">
                    <a href="{{route('admin.category.index')}}" class="nav-link pb-3">
                        分类列表
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('admin.category.create')}}" class="nav-link pb-3
                     {{active_class(if_route('admin.category.edit'),'active')}}">
                        编辑分类
                    </a>
                </li>
            </ul>
        </div>
        <form action="{{route('admin.category.update',$category)}}" method="post">
            @csrf
            @method('PUT')
            <div class="card-body">
                <div class="card">
                    <div class="card-header">
                        基本设置
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label>分类名称</label>
                            <input type="text" name="title" value="{{$category['title']}}" class="form-control"
                                   placeholder="请输入分类名称"
                                   aria-describedby="helpId">
                        </div>
                        <div class="form-group">
                            <label for="">父级分类</label>
                            <select class="form-control" name="parent_id">
                                <option value="0">顶级分类</option>
                                @foreach($categories as $cat)
                                    <option value="{{$cat['id']}}"
                                    {{$cat['_disabled']}} {{$cat['_selected']}}
                                    >{!! $cat['_title'] !!}</option>
                                @endforeach
                            </select>
                            <small id="helpId" class="text-muted">子类和本身是不能作为父类使用的</small>
                        </div>
                        <div class="form-group">
                            <label>分类描述</label>
                            <textarea name="description" style="resize: none" class="form-control"
                                      rows="3">{{$category['description']}}</textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer text-muted">
                <button class="btn btn-primary btn-sm">保存提交</button>
            </div>
        </form>
    </div>
@endsection

resources/views/category/index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="card">
        <div class="card-body">
            <ul class="nav nav-tabs nav-overflow header-tabs">
                <li class="nav-item">
                    <a href="{{route('admin.category.index')}}"
                       class="nav-link pb-3  {{active_class(if_route('admin.category.index'),'active')}}">
                        分类列表
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('admin.category.create')}}" class="nav-link pb-3">
                        添加分类
                    </a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            <table class="table text-center">
                <thead>
                <tr>
                    <th>编号</th>
                    <th>分类名称</th>
                    <th>父级分类名</th>
                    <th>创建时间</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                @foreach($categories as $category)
                    <tr>
                        <td>{{$category['id']}}</td>
                        <td>{{$category['title']}}</td>
                        <td>
                            @if($category['parent_id'] == 0)
                                顶级分类
                            @else
                                {!! $category->parent_name->title !!}
                            @endif
                        </td>
                        <td>
                            {{$category['created_at']->diffForHumans()}}
                        </td>
                        <td>
                            <div class="btn-group btn-group-sm" role="group" aria-label="First group">
                                <a href="{{route('admin.category.edit',$category)}}" class="btn btn-light">编辑分类</a>
                                <button type="button" class="btn btn-white" onclick="del(this)">删除分类</button>
                                <form type="button" action="{{route('admin.category.destroy',$category)}}"
                                      method="post">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div class="my--2"></div>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {{$categories->links()}}
            </ul>
        </nav>
    </div>
@endsection

@push('js')
    <script>
        function del(obj) {
            require(['hdjs'], function (hdjs) {
                hdjs.confirm("确定删除该分类吗？", function () {
                    $(obj).next().submit();
                })
            })
        }
    </script>
@endpush