routes/web.php
<?php
//Route::get('/', function () {
//    return view('welcome');
//});
// 前台首页路由
Route::group(['namespace'=>'Home','as'=>'home.'],function (){
    // 前台首页路由
    Route::get('/','HomeController@index')->name('index');
    // 详情页路由
    Route::get('/content/{good}/{product?}','HomeController@content')->name('content');
    // 列表页路由
    Route::get('/lists/{category}','HomeController@lists')->name('lists');

    // 前台登录、退出、注册路由
    Route::get('/login','LoginController@loginForm')->name('login');
    Route::post('/login','LoginController@login')->name('login');
    Route::get('/logout','LoginController@logout')->name('logout');
    Route::get('/regist','RegistController@regist')->name('regist');
    Route::post('/regist','RegistController@store')->name('regist');
    // 微信支付异步通知路由,异步是微信的请求，对于微信而言，不存在什么令牌一说，所以要想请求到laravel里面的数据，
    // 就应该把微信请求的路由规则加入白名单，即 中间件里面的 verifycsrftoken文件设置就可以了。
    Route::post('wxPayResult','PayController@wxPayResult')->name('wxPayResult');
});
/**
 *  需要验证的路由
 */
Route::group(['middleware'=>'auth.login','namespace'=>'Home','as'=>'home.'],function (){
    // 加入购物车路由
    Route::get('/addCart/{good}/{product}/{num}','CartController@addCart')->name('addCart');
    // 立即购买
    Route::post('quickBuy','CartController@quickBuy')->name('quickBuy');
    // 我的购物车
    Route::get('/myCart','CartController@myCart')->name('myCart');
    // 删除购物车数据路由
    Route::get('/deleteCart/{cart}','CartController@delete')->name('myCart.delete');
    // 购物车数量加1
    Route::get('/plus/{cart}','CartController@plus')->name('myCart.plus');
    // 购物车数量减1
    Route::get('/minus/{cart}','CartController@minus')->name('myCart.minus');
    // 个人中心路由
    Route::get('/center/{bianliang}','CenterController@index')->name('center');
    // 个人中心修改密码路由
    Route::put('/center/changePassword/','UserController@changPassword')->name('changePassword');
    // 个人中心修改个人信息的路由
    Route::put('/center/gerenXinxi','UserController@gerenXinxi')->name('gerenXinxi');
    // 个人中心收货人地址资源路由
    Route::resource('/center/address','AddressController');
    // 设置默认地址路由
    Route::get('/center/setDefault/{address}','AddressController@setDefault')->name('setDefault');
    // 去结算的订单列表页面
    Route::get('/order_list','OrderController@orders')->name('order_list');
    // 订单的资源路由
    Route::resource('/order','OrderController');
    // 异步删除我的订单路由
    Route::get('/delOrder/{order_id}','CenterController@delOrder')->name('delOrder');
    // 提交订单成功以后，跳转的支付订单路由
    Route::get('/pay/{order_bianhao}','PayController@index')->name('pay');
    //检测订单支付状态
    Route::post('checkOrderStatus','PayController@checkOrderStatus')->name('checkOrderStatus');
});
/*
 *【后台登录验证的路由组】
 */
Route::group(['middleware'=>'admin.auth','prefix'=>'admin','namespace'=>'Admin','as'=>'admin.'],function (){
    Route::get('/','AdminController@index')->name('index');
    // 分类管理资源路由
    Route::resource('/category','CategoryController');
    // 获取子分类的路由
    Route::get('/getSonCategory/{id}','CategoryController@getSonCategory')->name('getSonCategory');
    // 商品管理资源路由
    Route::resource('/goods','GoodsController');
    // 后台，订单管理路由
    Route::resource('order','OrderController');
    // 幻灯片管理
    Route::resource('slide','SlideController');
    // 权限列表路由
    Route::get('admin/permission','PermissionController@index')->name('permission');
    // 角色资源路由
    Route::resource('admin/role','RoleController');

});

/*
 * 【后台登录不需要验证的路由组】
 */
Route::group(['prefix'=>'admin','namespace'=>'Admin','as'=>'admin.'],function (){
    Route::get('/login','LoginController@loginForm')->name('login');
    Route::post('/login','LoginController@login')->name('login');
    Route::get('/logout','LoginController@logout')->name('logout');
});

/**
 * 公共控制器  图片上传类
 */
Route::group(
    ['prefix' => 'common', 'namespace' => 'Common', 'as' => 'common.'],
    function () {
        Route::any('uploader/make', 'UploaderController@make')->name('uploader.make');
        Route::any('uploader/lists', 'UploaderController@lists')->name('uploader.lists');
        // layui图片上传路由
        Route::any('uploader/layuiUpload','UploaderController@layuiUpload')->name('uploader.layuiUpload');
        // 发送验证码类
        Route::any('code/send','CodeController@send')->name('code.send');
    }
);

app/Http/Controllers/Home/AddressController.php
<?php

namespace App\Http\Controllers\Home;

use App\Http\Controllers\Controller;
use App\Models\Address;
use Illuminate\Http\Request;

class AddressController extends Controller
{
    // 保存方法
    public function store(Request $request)
    {
        $request['user_id'] = auth()->id();
        if ($request['is_default']) {
            Address::where('user_id', auth()->id())->update(['is_default' => 0]);
        }
        Address::create($request->all());

        return back()->with('success', '添加成功！');
    }

//    更新方法
    public function update(Request $request, Address $address)
    {
        if (isset($request['is_default'])) {
            Address::where('user_id', auth()->id())->update(['is_default' => 0]);
        } else {
            $request['is_default'] = 0;
        }
        $address->update($request->all());

        return back()->with('success', '编辑成功！');
    }

//    设置默认方法
    public function destroy(Address $address)
    {
        $address->delete();
        return back()->with('success', '删除成功！');
    }

    public function setDefault(Address $address)
    {
        Address::where('user_id', auth()->id())->update(['is_default' => 0]);
        $address->update(['is_default' => 1]);
        return back()->with('success', '设置成功！');
    }
}

app/Http/Controllers/Home/CartController.php
<?php

namespace App\Http\Controllers\Home;

use App\Http\Controllers\Controller;
use App\Models\Cart;
use App\Models\Goods;
use App\Models\Product;
use Illuminate\Http\Request;

class CartController extends Controller
{
    // 这里因为路由加了3个参数，所以这里也加入3个参数，分别表示： 商品-货品-数量
    // 因为这里涉及到了大量的运算，所以我们选择了vue来布局控制数量的变化
    public function addCart(Goods $good, Product $product, $num)
    {
        // 首先应该去表里面找，当前用户是否已经有加入购物车的数据
        $cart = Cart::where('user_id', auth()->id())->where('product_id', $product['id'])->first();
        // 如果已经有当前货品数据，就应该在原有的基础上进行修改，而不再是添加数据
        if ($cart) {
            $cart->update(
                [
                    'num' => $num + $cart['num'],
                    'xiaoji' => ($good['price'] + $product['add_price']) * ($num + $cart['num']),
                ]
            );
        } else {
            Cart::create(
                [
                    'goods_id' => $good['id'],
                    'product_id' => $product['id'],
                    'user_id' => auth()->id(),
                    'num' => $num,
                    'xiaoji' => ($good['price'] + $product['add_price']) * $num,
                ]
            );
        }
        return back()->with('success', '添加购物车成功！');
    }
    public function quickBuy(Request $request )
    {
        $good = Goods::where('id',$request->good)->first();
        $product = Product::where('id',$request->huopin)->first();
        // 首先应该去表里面找，当前用户是否已经有加入购物车的数据
        $cart = Cart::where('user_id', auth()->id())->where('product_id',$request->huopin)->first();
        // 如果已经有当前货品数据，就应该在原有的基础上进行修改，而不再是添加数据
        if ($cart) {
            $cart->update(
                [
                    'num' => $request->num,
                    'xiaoji' => $good['price'] * ($request->num),
                ]
            );
        } else {
            Cart::create(
                [
                    'goods_id' => $request->good,
                    'product_id' => $request->huopin,
                    'user_id' => auth()->id(),
                    'num' => $request->num,
                    'xiaoji' => $good['price'] * $request->num,
                ]
            );
        }
        $cart = Cart::where('product_id',$request->huopin)->first();
        return ['code'=>1,'msg'=>'添加购物车成功！','ids'=>$cart['id']];
    }

    // 我的购物车
    public function myCart()
    {
        // 把所有的商品和货品信息一起带过去，方便分配
        $carts = Cart::where('user_id', auth()->id())->with('goods', 'product')->get();
        // 购物车是多条数据，一个对象集合，所以要进行循环
        foreach($carts as $k=>$cart){
            // 给每一个购物车数据加一个附加属性，checked，默认为不选中状态
            $carts[$k]['checked'] = false;
        }
        return view('home.myCart.cart', compact('carts'));
    }

     //异步请求：删除购物车数据的方法
    public function delete(Cart $cart){
        $cart->delete();
        return ['valid'=>'1','message'=>'删除成功'];
    }

    // 异步请求增加购物车数量增加的方法
    public function plus(Cart $cart){
        $cart->update([
            'num'=> $cart['num']+1,
            'xiaoji'=>$cart->goods->price + $cart->product->add_price + $cart['xiaoji']
        ]);
        return ['valid'=>'1','message'=>''];
    }

    // 异步请求减少购物车数量数据的方法
    public function minus(Cart $cart){
            $cart->update([
                'num'=>$cart['num']-1,
                'xiaoji'=> $cart['xiaoji'] - $cart->goods->price - $cart->product->add_price
            ]);
        return ['valid'=>'1','message'=>''];
    }
}

app/Http/Controllers/Home/CenterController.php
<?php

namespace App\Http\Controllers\Home;

use App\Models\Address;
use App\Models\Cart;
use App\Models\Order;
use App\Models\Order_Detail;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CenterController extends Controller
{
    // 个人中心首页加载方法
    public function index($bianliang,User $user){
        // 获取当前用户信息
        $user = User::where('id',auth()->id())->first()->toArray();
        // 获取当前用户的地址信息
        $addresses = Address::where('user_id',auth()->id())->orderby('is_default','DESC')->get();
        // 获取购物车数据的
        $carts = Cart::where('user_id',auth()->id())->with('goods','product')->latest()->limit(2)->get();
        // 获取订单表中的数据
        $orders = Order::where('user_id',auth()->id())->latest()->get();

        return view('home.center.'.$bianliang,compact('user','addresses','carts','orders'));
    }
    // 个人中心：异步删除订单表数据的方法
    public function delOrder($order_id){
       $order = Order::where('id',$order_id);
       $order->delete();
       return ['code'=>1,'msg'=>'删除成功！'];
    }
}

app/Http/Controllers/Home/CommonController.php
<?php

namespace App\Http\Controllers\Home;

use App\Models\Goods;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\View;

class CommonController extends Controller
{
    public function __construct()
    {
        // 在商品表中随机去除4条商品，其他控制器通过继承该控制器就会优先加载到这些数据，所以这个很方便的
        // 会把一些公共的数据带到公共的页面上。只要继承了这个控制器就可以了。
        $goods = Goods::inRandomOrder()->limit(4)->get();
        View::share('share_goods', $goods);
    }
}

app/Http/Controllers/Home/HomeController.php
<?php

namespace App\Http\Controllers\Home;

use App\Models\Cart;
use App\Models\Category;
use App\Models\Goods;
use App\Models\Product;
use App\Models\Slide;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use phpDocumentor\Reflection\DocBlock\Tags\Covers;

class HomeController extends CommonController
{
    public function index(){
        // 获取轮播图数据
        $slides = Slide::latest()->limit(3)->get();
        // 获取当前用户的购物车数据，只要获取到购物车数据用with方法就可以把关联的商品，和货品一同带过去
        $carts =Cart::where('user_id',auth()->id())->latest()->with('goods','product')->get();
        // 获取顶级分类数据，目的是为了循环每一个一级分类（首页大块内容部分：如手机、电脑等）
        /**
         * 获取每分类数据，及其二级分类下的所有三级分类数据
         */
        $categories = Category::where('parent_id',0)->get();
        // 特色商品随机抽取4个分配到页面,在页面底部左侧部分 特色商品部分
        $goods = Goods::inRandomOrder()->limit(4)->get()->toArray();

        // 热门推荐商品，利用表里面的推荐字段，可以用where条件获取到推荐商品，取出随机5条
        $commend_goods = Goods::where('is_commend',1)->inRandomOrder()->limit(5)->get();

        return view('home.index',compact('categories','carts','slides','goods','commend_goods'));
    }

    // 列表页
    public function lists(Category $category){
        $carts =Cart::where('user_id',auth()->id())->latest()->with('goods','product')->get();
        $fatherCategory = $category->getFatherCategory();
        // 找当前分类下的所有商品数据
       $goods = $category->getCategoryGoods();
        return view('home.lists',compact('category','goods','fatherCategory','carts'));
    }

    // 详情页
    public function content(Goods $good,$product=0){
        $carts =Cart::where('user_id',auth()->id())->latest()->with('goods','product')->get();
        // 为了在详情页展示商品的所在分类，那么就应该先求出每一个商品所在的三级分类，然后再求出该3级分类的父级分类
        // 就可以实现分类，这样目的是为了获取分类并且在点击链接时，能够跳转到对应的分类所在的列表页
        // 找当前商品的三级分类 ,，找到最底层的分类，就可以找它的父级分类了
        $category = Category::find($good['category_id'][2]);
        $fatherCategory = array_reverse($category->getFatherCategory());
        // 判断是否传递了货品ID ，这样设计是为了实现页面的跳转来选择不同的货品属性
        if($product){
            $huopin = Product::find($product);

        }else{
            // 默认选中商品的第一个货品属性
            $huopin = Product::where('goods_id',$good['id'])->first();
        }
        return view('home.content',compact('good','huopin','fatherCategory','carts'));
    }

}

app/Http/Controllers/Home/LoginController.php
<?php

namespace App\Http\Controllers\Home;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LoginController extends Controller
{
    public function __construct()
    {
         $this->middleware('home.checkLogin')->except(['logout']);
    }

    public function loginForm()
    {
        return view('home.login.login');
    }

    //登录验证方法
    public function login(Request $request)
    {
        $status = \Auth::attempt(
            [
                'email' => $request['email'],
                'password' => $request['password'],
            ]
        );
        if ($status) {
            return redirect(route('home.index'))->with('success', '登录成功！');
        }
        return back()->with('error', '账号或密码错误');
    }

    // 退出登录
    public function logout()
    {
        auth()->logout();
        return redirect(route('home.index'))->with('success', '退出成功');
    }
}

app/Http/Controllers/Home/OrderController.php
<?php

namespace App\Http\Controllers\Home;

use App\Http\Controllers\Controller;
use App\Models\Address;
use App\Models\Cart;
use App\Models\Order;
use App\Models\Order_Detail;
use Illuminate\Http\Request;

class OrderController extends Controller
{

    public function index(Order $order)
    {

    }

    public function create()
    {

    }

    public function store(Request $request, Order $order)
    {
        //获取post异步请求发送过来的数据，仍然是购物车的数据编号
        $ids = $request->ids;
        // 把字符串拆分成一个数组
        $arr_ids = explode(',', $ids);
        //用购物车模型去找id在传过来id数组中的数据 ，就可以获取所有的购物车数据，用sum方法，把所有对象集合的某一个字段值
        // 的和求出来，就可以得到所有小计的和 ，就是所有商品的总价钱了。用zongjia来表示
        $zongjia = Cart::whereIn('id', $arr_ids)->get()->sum('xiaoji');

        // 因为是往订单表里面插入数据，所以要实例化一个模型对象
        $order->address_id = $request['address_id'];
        $order->user_id = auth()->id();
        $order->total_price = $zongjia;
        $order->order_bianhao = time().auth()->id();
        $order->save();
//        dd($order);

        // 往订单明细表添加对应的数据，因为是订单明细存放着商品，和货品信息所以我们这里要循环购物车数据，通过关联
        // 获取到对应的商品和货品信息，存在订单明细表里面
        $cartData = Cart::whereIn('id', $arr_ids)->get();
        foreach ($cartData as $v) {
            // 实例化一个订单明细对象，修改对象字段，保存新字段值
            $order_detail = new Order_Detail();
            $order_detail->order_id = $order->id;
            $order_detail->goods_id = $v->goods_id;
            $order_detail->product_id = $v->product_id;
            $order_detail->num = $v->num;
//            dd($order_detail);
            $order_detail->save();
        }

        //同时清空购物车数据
        $carts = Cart::whereIn('id',$arr_ids)->get();
        foreach($carts as $cart){
            $cart->delete();
        };

        // 异步要求返回
        return [
            'code' => 1,
            'message' => '订单生成成功',
            // 注意，我们这里异步请求完成以后不光要返回一个状态码，还要返回订单编号，因为我们要进行页面跳转，需要把
            // 订单编号给传递过去，所以这里我们采用了data属性来给前台返回一条数据里面就包含了订单编号这个变量
            'data' => [
                'order_bianhao' => $order->order_bianhao,
            ],
        ];
    }

    public function show(Order $order)
    {
        //
    }

    public function edit(Order $order)
    {
        //
    }

    public function update(Request $request, Order $order)
    {
        //
    }


    public function destroy(Request $request,Order $order)
    {

    }

    // 展示订单页面的方法
    public function orders(Request $request)
    {
        // 获取当前登录用户的收获地址
        $addresses = Address::where('user_id', auth()->id())->get();
        // 获取默认被选中的地址
        $defaultAddress = Address::where('user_id', auth()->id())->where('is_default', '1')->first()->toArray();
        // 获取从get参数传递过来的购物车ID ，把它转成一个数组
        $str_ids = rtrim($request->query('ids'), ',');
        $ids = explode(',', $str_ids);
        // 按照get传递过来的参数，从购物车表里面找到对应的数据
        $carts = Cart::whereIn('id', $ids)->get();
        // 计算购物车商品的总价
        $totalPrice = Cart::whereIn('id', $ids)->sum('xiaoji');
        return view(
            'home.order.order',
            compact('addresses', 'str_ids', 'ids', 'carts', 'totalPrice', 'defaultAddress')
        );
    }
}

resources/views/home/layouts/master.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>在线商城</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" type="text/css" href="{{asset('org/home/css')}}/index.css">
    <style>
        .tes_shangp_neir_k h2 {
            font-size: 12px;
        }
        .rem_shangp_beij_k img{
            border:1px solid #fff0ff;
            width:214px;
            height:204px;
        }
        .rem_shangp_beij_k .title{
            max-width: 214px;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }
    </style>

    @stack('css')
    <script src="{{asset('org/home/js')}}/jquery-1.11.3.min.js"></script>
    <script src="{{asset('org/home/js')}}/index.js"></script>
    <script type="text/javascript" src="{{asset('org/home/js')}}/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="{{asset('org/home/js')}}/jquery.SuperSlide.2.1.1.source.js"></script>
    <script src="https://cdn.bootcss.com/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script>
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
    </script>
    @stack('js')
</head>
<body>
@include('layouts._home_message')
<!--侧边-->
<div class="jdm-toolbar-wrap J-wrap">
    <div class="jdm-toolbar J-toolbar">
        <div class="jdm-toolbar-panels J-panel"></div>
        <div class="jdm-toolbar-tabs J-tab">
            <div data-type="bar" class="J-trigger jdm-toolbar-tab jdm-tbar-tab-ger">
                <i class="tab-ico"></i>
                <a href="{{route('home.center','basic')}}"><em class="tab-text">个人中心</em></a>
            </div>
            <div data-type="bar" class="J-trigger jdm-toolbar-tab jdm-tbar-tab-cart">
                <i class="tab-ico"></i>
                <a href="{{route('home.myCart')}}"><em class="tab-text">购物车</em></a>
            </div>
            <div data-type="bar" clstag="h|keycount|cebianlan_h_follow|btn"
                 class="J-trigger jdm-toolbar-tab jdm-tbar-tab-follow" data-name="follow" data-login="true">
                <i class="tab-ico"></i>
                <em class="tab-text">我的关注</em>
            </div>
        </div>
        <div class="J-trigger jdm-toolbar-tab jdm-tbar-tab-message" data-name="message"><a target="_blank" href="#">
                <i class="tab-ico"></i>
                <em class="tab-text">我的消息
                </em></a>
        </div>
    </div>
    <div class="jdm-toolbar-footer">
        <div data-type="link" id="#top" class="J-trigger jdm-toolbar-tab jdm-tbar-tab-top">
            <a href="#" clstag="h|keycount|cebianlan_h|top">
                <i class="tab-ico"></i>
                <em class="tab-text">顶部</em>
            </a>
        </div>
    </div>
    <div class="jdm-toolbar-mini"></div>
    <div id="J-toolbar-load-hook" clstag="h|keycount|cebianlan_h|load"></div>
</div>
{{--引入头部位置--}}
<div id="header">
    <div class="header-box">
        <h3 class="huany">欢迎您的到来！</h3>
        @auth
            <ul class="header-right">
                <li class="denglu">Hi~<a class="red"
                                         href="{{route('home.center','index')}}">{{auth()->user()->name}}</a> <a
                        href="{{route('home.logout')}}">【退出登录】</a></li>
            </ul>
        @else
            <ul class="header-right">
                <li class="denglu">Hi~<a class="red" href="{{route('home.login')}}">请登录!</a> <a
                        href="{{route('home.regist')}}">[免费注册]</a></li>
            </ul>
        @endauth
    </div>
</div>
<!--搜索栏-->
<div class="toub_beij">
    <div class="logo"><a href="./"><img src="{{asset('org/home')}}/images/logo11.png"></a></div>
    <div class="search">
        <input type="text" value="家电一折抢" class="text" id="textt">
        <button class="button">搜索</button>
    </div>
    <div class="right">
        <i class="gw-left"></i>
        <i class="gw-right"></i>
        <div class="sc">
            @if(isset($carts))
                <i class="gw-count">{{count($carts)}}</i>
            @endif
            <i class="sd"></i>
        </div>
        <a href="{{route('home.myCart')}}">我的购物车</a>
        <div class="dorpdown-layer">
            <ul>
                @if(isset($carts) && count($carts)>0)
                    <li class="meiyou" style="width:90%;">
                        <span style="font-size: 14px;font-weight: bold"> 最近加入的宝贝</span>
                    </li>
                @else
                    <li class="meiyou" style="width:90%;">
                        <span style="font-size: 14px;font-weight: bold"> 您还没有收藏任何商品</span>
                    </li>
                @endif
                @if(isset($carts))
                    @foreach($carts as $k=>$cart)
                            <li class="meiyou"
                                style="width:90%;overflow: hidden;white-space:nowrap;text-overflow:ellipsis;">
                                <img style="width:57px;height:49px;" src="{{$cart->goods->pics[0]}}">
                                <span><a target="_blank" href="{{route('home.myCart')}}"
                                         style="font-size: 12px;">{{$cart->goods->title}}</a></span>
                            </li>
                    @endforeach
                @endif
            </ul>
        </div>
    </div>
    <div class="hotwords">
        <a class="biaoti">热门搜索：</a>
        <a href="#">新款连衣裙</a>
        <a href="#">四件套</a>
        <a href="#">潮流T恤</a>
        <a href="#">时尚女鞋</a>
        <a href="#">乐1</a>
        <a href="#">特步女鞋</a>
        <a href="#">威士忌</a>
    </div>
</div>

{{--主体部分占位--}}
@yield('content')

<!--底部-->
<div class="dib_beij">
    <div class="dib_jvz_beij">
        <div class="shangp_baoz">
            <p>本地购物&nbsp;&nbsp;看得见的商品</p>
            <p class="beng1">正品行货&nbsp;&nbsp;购物无忧</p>
            <p class="beng2">低价实惠&nbsp;&nbsp;帮你省钱</p>
            <p class="beng3">本地直发&nbsp;&nbsp;专业配送</p>
        </div>
        <div class="zhongj_youx">
            <div class="lieb_daoh">
                <h4>物流配送</h4>
                <ul>
                    <li><a href="javascript:;">配送查询</a></li>
                    <li><a href="javascript:;">配送服务</a></li>
                    <li><a href="javascript:;">配送费用</a></li>
                    <li><a href="javascript:;">配送时效</a></li>
                    <li><a href="javascript:;">签收与验货</a></li>
                </ul>
            </div>
            <div class="lieb_daoh">
                <h4>支付与账户</h4>
                <ul>
                    <li><a href="javascript:;">货到付款</a></li>
                    <li><a href="javascript:;">在线支付</a></li>
                    <li><a href="javascript:;">门店支付</a></li>
                    <li><a href="javascript:;">账户安全</a></li>
                </ul>
            </div>
            <div class="lieb_daoh">
                <h4>购物帮助</h4>
                <ul>
                    <li><a href="javascript:;">购物保障</a></li>
                    <li><a href="javascript:;">购物流程</a></li>
                    <li><a href="javascript:;">焦点问题</a></li>
                    <li><a href="javascript:;">联系我们</a></li>
                </ul>
            </div>
            <div class="lieb_daoh">
                <h4>售后服务</h4>
                <ul>
                    <li><a href="javascript:;">退换货服务</a></li>
                    <li><a href="javascript:;">退款说明</a></li>
                    <li><a href="javascript:;">专业维修</a></li>
                    <li><a href="javascript:;">延保服务</a></li>
                    <li><a href="javascript:;">家电回收</a></li>
                </ul>
            </div>
            <div class="lieb_daoh">
                <div class="kef_dianh">
                    <p>客服电话</p><span>15110853679</span>
                </div>
                <div class="kef_dianh kef_dianh_youx">
                    <p>意见收集邮箱</p>
                    <p>237618121@qq.com</p>
                </div>
            </div>
            <div class="lieb_daoh lieb_daoh_you">
                <div class="erw_ma_beij">
                    <div class="erw_m">
                        <h1><img style="width:127px;height:127px;" src="/images/nopic.jpg"></h1>
                        <span>扫码下载通城客户端</span>
                    </div>
                    <div class="erw_m">
                        <h1><img src="/images/nopic.jpg"></h1>
                        <span>扫码下载通城客户端</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>